name = "miniflux-ai"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-06"

[[kv_namespaces]]
binding = "entries"
id = "<insert-your-namespace-id>"

[build]
command = "cargo install -q worker-build && worker-build --release"

[triggers]
crons = ["*/15 * * * *"]

[vars]
CF_AI_MODEL = "@cf/facebook/bart-large-cnn"
